apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fabric-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fabric-test
    spec:
      containers:
      - name: fabric-test
        image: hyperledger/fabric-test:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash"]
        volumeMounts:
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
          name: crypto-config-volume
        - mountPath: /etc/hyperledger/fabric/crypto-config
          name: crypto-config-volume
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto-config.yaml
          name: crypto-config-yaml-volume
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
          name: scripts-volume
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
          name: channel-artifacts-volume
        - mountPath: /opt/gopath/src/github.com/hyperledger/fabric/configtx.yaml
          name: configtx-volume
        env:
        - name: CORE_PEER_ID
          value: "fabric-test"
        - name: CORE_PEER_ADDRESS
          value: "fabric-peer0-org1:7051"
        - name: CORE_PEER_LOCALMSPID
          value: "Org1MSP"
        - name: CORE_PEER_TLS_ENABLED
          value: "false"
        - name: CORE_PEER_TLS_CERT_FILE
          value: "/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt"
        - name: CORE_PEER_TLS_KEY_FILE
          value: "/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key"
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: "/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt"
        - name: CORE_PEER_MSPCONFIGPATH
          value: "/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp"
      volumes:
      - name: crypto-config-volume
        hostPath:
          path: /opt/e2e_cli/crypto-config
      - name: crypto-config-yaml-volume
        hostPath:
          path: /opt/e2e_cli/crypto-config.yaml
      - name: scripts-volume
        hostPath:
          path: /opt/scripts
      - name: channel-artifacts-volume
        hostPath:
          path: /opt/e2e_cli/channel-artifacts
      - name: configtx-volume
        hostPath:
          path: /opt/e2e_cli/configtx.yaml
