apiVersion: v1
kind: Service
metadata:
  name: fabric-kafka
  labels:
    app: fabric-kafka
spec:
  ports:
  - port: 9092
    targetPort: 9092
  selector:
    app: fabric-kafka
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fabric-kafka
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: fabric-kafka
    spec:
      containers:
      - name: fabric-kafka
        image: hyperledger/fabric-kafka
        imagePullPolicy: Never
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE
          value: "false"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "fabric-zookeeper:2181"
