apiVersion: v1
kind: Service
metadata:
  name: fabric-offchaindb
  labels:
    app: fabric-offchaindb
spec:
  ports:
  - port: 5984
    targetPort: 5984
  selector:
    app: fabric-offchaindb
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fabric-offchaindb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fabric-offchaindb
    spec:
      containers:
      - name: fabric-offchaindb
        image: hyperledger/fabric-couchdb
        imagePullPolicy: Never
        ports:
        - containerPort: 5984
        env:
        - name: COUCHDB_USER
          value: "admin"
        - name: COUCHDB_PASSWORD
          value: "password"
