apiVersion: v1
kind: Service
metadata:
  name: fabric-ca-org2
  labels:
    app: fabric-ca-org2
spec:
  ports:
  - port: 7054
    targetPort: 7054
  selector:
    app: fabric-ca-org2
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fabric-ca-org2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fabric-ca-org2
    spec:
      containers:
      - name: fabric-ca-org2
        image: hyperledger/fabric-ca
        imagePullPolicy: Never
        ports:
        - containerPort: 7054
        command: ["fabric-ca-server", "start", "--ca.certfile", "/etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem", "--ca.keyfile", "/etc/hyperledger/fabric-ca-server-config/b6024479226ac3b83eab5a9d808f203ad0a6f47a0c2c85fbcd4fdf43de308f1e_sk", "-b", "admin:adminpw", "-d"]
        volumeMounts:
        - mountPath: /etc/hyperledger/fabric-ca-server-config
          name: org2-ca-volume
        env:
        - name: FABRIC_CA_HOME
          value: "/etc/hyperledger/fabric-ca-server"
        - name: FABRIC_CA_SERVER_CA_NAME
          value: "ca-org2"
        - name: FABRIC_CA_SERVER_TLS_ENABLED
          value: "true"
        - name: FABRIC_CA_SERVER_TLS_CERTFILE
          value: "/etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem"
        - name: FABRIC_CA_SERVER_TLS_KEYFILE
          value: "/etc/hyperledger/fabric-ca-server-config/b6024479226ac3b83eab5a9d808f203ad0a6f47a0c2c85fbcd4fdf43de308f1e_sk"
      volumes:
      - name: org2-ca-volume
        hostPath:
          path: /opt/e2e_cli/crypto-config/peerOrganizations/org2.example.com/ca
