apiVersion: v1
kind: Service
metadata:
  name: fabric-ca
  labels:
    app: fabric-ca
spec:
  ports:
  - port: 7054
    targetPort: 7054
  selector:
    app: fabric-ca
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fabric-ca
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fabric-ca
    spec:
      containers:
      - name: fabric-ca
        image: hyperledger/fabric-ca:x86_64-1.0.0-alpha2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7054
        command: ["fabric-ca-server", "start", "-b", "admin:adminpw"]
